package com.yueshimall.dao;

import com.yueshimall.dataobject.CUSTOMER;
import org.springframework.stereotype.Component;

@Component

public interface CUSTOMERMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    int deleteByPrimaryKey(Integer customerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    int insert(CUSTOMER record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    int insertSelective(CUSTOMER record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    CUSTOMER selectByPrimaryKey(Integer customerid);

    CUSTOMER selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    int updateByPrimaryKeySelective(CUSTOMER record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    int updateByPrimaryKey(CUSTOMER record);
}