package com.yueshimall.dao;

import com.yueshimall.dataobject.ORDERGOODLIST;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ORDERGOODLISTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int deleteByPrimaryKey(Integer idorderGood);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int insert(ORDERGOODLIST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int insertSelective(ORDERGOODLIST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    ORDERGOODLIST selectByPrimaryKey(Integer idorderGood);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int updateByPrimaryKeySelective(ORDERGOODLIST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int updateByPrimaryKey(ORDERGOODLIST record);

    List<ORDERGOODLIST> selectall(Integer orderid);
}