package com.yueshimall.dao;

import com.yueshimall.dataobject.PAYMENT;
import org.springframework.stereotype.Component;

@Component
public interface PAYMENTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int deleteByPrimaryKey(Integer idpayment);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int insert(PAYMENT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int insertSelective(PAYMENT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    PAYMENT selectByPrimaryKey(Integer idpayment);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int updateByPrimaryKeySelective(PAYMENT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    int updateByPrimaryKey(PAYMENT record);
}