package com.yueshimall.dao;

import com.yueshimall.dataobject.SELLERSTORE;

public interface SELLERSTOREMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerstore
     *
     * @mbg.generated Fri Feb 14 20:16:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerstore
     *
     * @mbg.generated Fri Feb 14 20:16:24 CST 2020
     */
    int insert(SELLERSTORE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerstore
     *
     * @mbg.generated Fri Feb 14 20:16:24 CST 2020
     */
    int insertSelective(SELLERSTORE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerstore
     *
     * @mbg.generated Fri Feb 14 20:16:24 CST 2020
     */
    SELLERSTORE selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerstore
     *
     * @mbg.generated Fri Feb 14 20:16:24 CST 2020
     */
    int updateByPrimaryKeySelective(SELLERSTORE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerstore
     *
     * @mbg.generated Fri Feb 14 20:16:24 CST 2020
     */
    int updateByPrimaryKey(SELLERSTORE record);
}