package com.yueshimall.dao;

import com.yueshimall.dataobject.SHOPPINGLIST;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SHOPPINGLISTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_goodlist
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    int deleteByPrimaryKey(Integer shoppingGoodlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_goodlist
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    int insert(SHOPPINGLIST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_goodlist
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    int insertSelective(SHOPPINGLIST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_goodlist
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    SHOPPINGLIST selectByPrimaryKey(Integer shoppingGoodlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_goodlist
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    int updateByPrimaryKeySelective(SHOPPINGLIST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_goodlist
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    int updateByPrimaryKey(SHOPPINGLIST record);

    List<SHOPPINGLIST> selectall(Integer shoppingid);

    List<SHOPPINGLIST> selected(Integer shoppingid,Integer selected);
}