package com.yueshimall.dao;

import com.yueshimall.dataobject.SPU_COM;

import java.util.List;

public interface SPU_COMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_complete
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    int deleteByPrimaryKey(Integer spuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_complete
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    int insert(SPU_COM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_complete
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    int insertSelective(SPU_COM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_complete
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    SPU_COM selectByPrimaryKey(Integer spuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_complete
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    int updateByPrimaryKeySelective(SPU_COM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_complete
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    int updateByPrimaryKey(SPU_COM record);
    List<SPU_COM> listspu();
}