package com.yueshimall.dao;

import com.yueshimall.dataobject.SPU;

import java.util.List;

public interface SPUMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_basic
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_basic
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    int insert(SPU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_basic
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    int insertSelective(SPU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_basic
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    SPU selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_basic
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    int updateByPrimaryKeySelective(SPU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_basic
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    int updateByPrimaryKey(SPU record);

    List<SPU> listgood();
}