package com.yueshimall.dataobject;

public class CUSTOMER {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customerid
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.address
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.telephone
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.password
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.name
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.cardnumber
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private String cardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.viplevel
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    private Integer viplevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customerid
     *
     * @return the value of customer_info.customerid
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customerid
     *
     * @param customerid the value for customer_info.customerid
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.address
     *
     * @return the value of customer_info.address
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.address
     *
     * @param address the value for customer_info.address
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.telephone
     *
     * @return the value of customer_info.telephone
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.telephone
     *
     * @param telephone the value for customer_info.telephone
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.password
     *
     * @return the value of customer_info.password
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.password
     *
     * @param password the value for customer_info.password
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.name
     *
     * @return the value of customer_info.name
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.name
     *
     * @param name the value for customer_info.name
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.cardnumber
     *
     * @return the value of customer_info.cardnumber
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public String getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.cardnumber
     *
     * @param cardnumber the value for customer_info.cardnumber
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber == null ? null : cardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.viplevel
     *
     * @return the value of customer_info.viplevel
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public Integer getViplevel() {
        return viplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.viplevel
     *
     * @param viplevel the value for customer_info.viplevel
     *
     * @mbggenerated Thu Jan 02 21:36:55 CST 2020
     */
    public void setViplevel(Integer viplevel) {
        this.viplevel = viplevel;
    }
}