package com.yueshimall.dataobject;

import java.util.Date;

public class ORDER {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderflag.idorder
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    private Integer idorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderflag.create_time
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderflag.shoppingid
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    private Integer shoppingid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderflag.idorder
     *
     * @return the value of orderflag.idorder
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    public Integer getIdorder() {
        return idorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderflag.idorder
     *
     * @param idorder the value for orderflag.idorder
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderflag.create_time
     *
     * @return the value of orderflag.create_time
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderflag.create_time
     *
     * @param createTime the value for orderflag.create_time
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderflag.shoppingid
     *
     * @return the value of orderflag.shoppingid
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    public Integer getShoppingid() {
        return shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderflag.shoppingid
     *
     * @param shoppingid the value for orderflag.shoppingid
     *
     * @mbggenerated Thu Jan 16 20:58:09 CST 2020
     */
    public void setShoppingid(Integer shoppingid) {
        this.shoppingid = shoppingid;
    }
}