package com.yueshimall.dataobject;

public class ORDERGOODLIST {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_good.idorder_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer idorderGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_good.orderid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_good.good_number
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer goodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_good.good_price
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer goodPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_good.goodid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer goodid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_good.idorder_good
     *
     * @return the value of order_good.idorder_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getIdorderGood() {
        return idorderGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_good.idorder_good
     *
     * @param idorderGood the value for order_good.idorder_good
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setIdorderGood(Integer idorderGood) {
        this.idorderGood = idorderGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_good.orderid
     *
     * @return the value of order_good.orderid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_good.orderid
     *
     * @param orderid the value for order_good.orderid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_good.good_number
     *
     * @return the value of order_good.good_number
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getGoodNumber() {
        return goodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_good.good_number
     *
     * @param goodNumber the value for order_good.good_number
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setGoodNumber(Integer goodNumber) {
        this.goodNumber = goodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_good.good_price
     *
     * @return the value of order_good.good_price
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getGoodPrice() {
        return goodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_good.good_price
     *
     * @param goodPrice the value for order_good.good_price
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setGoodPrice(Integer goodPrice) {
        this.goodPrice = goodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_good.goodid
     *
     * @return the value of order_good.goodid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_good.goodid
     *
     * @param goodid the value for order_good.goodid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }
}