package com.yueshimall.dataobject;

import java.util.Date;

public class PAYMENT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.idpayment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer idpayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.customerid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.time
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.status
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.orderid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.idpayment
     *
     * @return the value of payment.idpayment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getIdpayment() {
        return idpayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.idpayment
     *
     * @param idpayment the value for payment.idpayment
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setIdpayment(Integer idpayment) {
        this.idpayment = idpayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.customerid
     *
     * @return the value of payment.customerid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.customerid
     *
     * @param customerid the value for payment.customerid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.time
     *
     * @return the value of payment.time
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.time
     *
     * @param time the value for payment.time
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.status
     *
     * @return the value of payment.status
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.status
     *
     * @param status the value for payment.status
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.orderid
     *
     * @return the value of payment.orderid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.orderid
     *
     * @param orderid the value for payment.orderid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}