package com.yueshimall.dataobject;

public class SHOPPING {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.idshopping
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer idshopping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.customerid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    private Integer customerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.idshopping
     *
     * @return the value of shopping.idshopping
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getIdshopping() {
        return idshopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.idshopping
     *
     * @param idshopping the value for shopping.idshopping
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setIdshopping(Integer idshopping) {
        this.idshopping = idshopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.customerid
     *
     * @return the value of shopping.customerid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.customerid
     *
     * @param customerid the value for shopping.customerid
     *
     * @mbggenerated Thu Jan 16 15:42:11 CST 2020
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }
}