package com.yueshimall.dataobject;

public class SHOPPINGLIST {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.shopping_goodlistid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer shoppingGoodlistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.goodnumber
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer goodnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.goodprice
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer goodprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.sellerid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.goodid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.shoppingid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer shoppingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.selectflag
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private Integer selectflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goodlist.goodattribute
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    private String goodattribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.shopping_goodlistid
     *
     * @return the value of shopping_goodlist.shopping_goodlistid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getShoppingGoodlistid() {
        return shoppingGoodlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.shopping_goodlistid
     *
     * @param shoppingGoodlistid the value for shopping_goodlist.shopping_goodlistid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setShoppingGoodlistid(Integer shoppingGoodlistid) {
        this.shoppingGoodlistid = shoppingGoodlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.goodnumber
     *
     * @return the value of shopping_goodlist.goodnumber
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getGoodnumber() {
        return goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.goodnumber
     *
     * @param goodnumber the value for shopping_goodlist.goodnumber
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setGoodnumber(Integer goodnumber) {
        this.goodnumber = goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.goodprice
     *
     * @return the value of shopping_goodlist.goodprice
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getGoodprice() {
        return goodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.goodprice
     *
     * @param goodprice the value for shopping_goodlist.goodprice
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setGoodprice(Integer goodprice) {
        this.goodprice = goodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.sellerid
     *
     * @return the value of shopping_goodlist.sellerid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.sellerid
     *
     * @param sellerid the value for shopping_goodlist.sellerid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setSellerid(Integer sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.goodid
     *
     * @return the value of shopping_goodlist.goodid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.goodid
     *
     * @param goodid the value for shopping_goodlist.goodid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.shoppingid
     *
     * @return the value of shopping_goodlist.shoppingid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getShoppingid() {
        return shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.shoppingid
     *
     * @param shoppingid the value for shopping_goodlist.shoppingid
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setShoppingid(Integer shoppingid) {
        this.shoppingid = shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.selectflag
     *
     * @return the value of shopping_goodlist.selectflag
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public Integer getSelectflag() {
        return selectflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.selectflag
     *
     * @param selectflag the value for shopping_goodlist.selectflag
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setSelectflag(Integer selectflag) {
        this.selectflag = selectflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodlist.goodattribute
     *
     * @return the value of shopping_goodlist.goodattribute
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public String getGoodattribute() {
        return goodattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodlist.goodattribute
     *
     * @param goodattribute the value for shopping_goodlist.goodattribute
     *
     * @mbggenerated Fri Jan 17 20:36:29 CST 2020
     */
    public void setGoodattribute(String goodattribute) {
        this.goodattribute = goodattribute == null ? null : goodattribute.trim();
    }
}