package com.yueshimall.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class SKU {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.id
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.spu_id
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private Integer spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.price
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.stock
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.sales
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.attributes1
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private String attributes1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.attributes2
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private String attributes2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.attributes3
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private String attributes3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.attributes4
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private String attributes4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.create_time
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.update_time
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.id
     *
     * @return the value of sku.id
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.id
     *
     * @param id the value for sku.id
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.spu_id
     *
     * @return the value of sku.spu_id
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.spu_id
     *
     * @param spuId the value for sku.spu_id
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.price
     *
     * @return the value of sku.price
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.price
     *
     * @param price the value for sku.price
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.stock
     *
     * @return the value of sku.stock
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.stock
     *
     * @param stock the value for sku.stock
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.sales
     *
     * @return the value of sku.sales
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.sales
     *
     * @param sales the value for sku.sales
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.attributes1
     *
     * @return the value of sku.attributes1
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public String getAttributes1() {
        return attributes1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.attributes1
     *
     * @param attributes1 the value for sku.attributes1
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setAttributes1(String attributes1) {
        this.attributes1 = attributes1 == null ? null : attributes1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.attributes2
     *
     * @return the value of sku.attributes2
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public String getAttributes2() {
        return attributes2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.attributes2
     *
     * @param attributes2 the value for sku.attributes2
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setAttributes2(String attributes2) {
        this.attributes2 = attributes2 == null ? null : attributes2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.attributes3
     *
     * @return the value of sku.attributes3
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public String getAttributes3() {
        return attributes3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.attributes3
     *
     * @param attributes3 the value for sku.attributes3
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setAttributes3(String attributes3) {
        this.attributes3 = attributes3 == null ? null : attributes3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.attributes4
     *
     * @return the value of sku.attributes4
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public String getAttributes4() {
        return attributes4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.attributes4
     *
     * @param attributes4 the value for sku.attributes4
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setAttributes4(String attributes4) {
        this.attributes4 = attributes4 == null ? null : attributes4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.create_time
     *
     * @return the value of sku.create_time
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.create_time
     *
     * @param createTime the value for sku.create_time
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.update_time
     *
     * @return the value of sku.update_time
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.update_time
     *
     * @param updateTime the value for sku.update_time
     *
     * @mbg.generated Tue Dec 10 20:52:35 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}