package com.yueshimall.dataobject;

public class SPU {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.id
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.name
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.subtitle
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.sort
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.price
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.topprice
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private Double topprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_basic.imgUrl
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.id
     *
     * @return the value of spu_basic.id
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.id
     *
     * @param id the value for spu_basic.id
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.name
     *
     * @return the value of spu_basic.name
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.name
     *
     * @param name the value for spu_basic.name
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.subtitle
     *
     * @return the value of spu_basic.subtitle
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.subtitle
     *
     * @param subtitle the value for spu_basic.subtitle
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.sort
     *
     * @return the value of spu_basic.sort
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.sort
     *
     * @param sort the value for spu_basic.sort
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.price
     *
     * @return the value of spu_basic.price
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.price
     *
     * @param price the value for spu_basic.price
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.topprice
     *
     * @return the value of spu_basic.topprice
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public Double getTopprice() {
        return topprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.topprice
     *
     * @param topprice the value for spu_basic.topprice
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setTopprice(Double topprice) {
        this.topprice = topprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_basic.imgUrl
     *
     * @return the value of spu_basic.imgUrl
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_basic.imgUrl
     *
     * @param imgurl the value for spu_basic.imgUrl
     *
     * @mbg.generated Sun Dec 08 20:08:22 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}