package com.yueshimall.dataobject;

import java.util.Date;

public class SPU_COM {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.spu_id
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private Integer spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.salas
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private Integer salas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.stock
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.attribute1
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String attribute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.attribute2
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String attribute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.attribute3
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String attribute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.attribute4
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String attribute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.description
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.photolist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String photolist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.videolist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String videolist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.reservelist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private String reservelist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.create_time
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu_complete.update_time
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.spu_id
     *
     * @return the value of spu_complete.spu_id
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.spu_id
     *
     * @param spuId the value for spu_complete.spu_id
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.salas
     *
     * @return the value of spu_complete.salas
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public Integer getSalas() {
        return salas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.salas
     *
     * @param salas the value for spu_complete.salas
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setSalas(Integer salas) {
        this.salas = salas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.stock
     *
     * @return the value of spu_complete.stock
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.stock
     *
     * @param stock the value for spu_complete.stock
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.attribute1
     *
     * @return the value of spu_complete.attribute1
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.attribute1
     *
     * @param attribute1 the value for spu_complete.attribute1
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.attribute2
     *
     * @return the value of spu_complete.attribute2
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.attribute2
     *
     * @param attribute2 the value for spu_complete.attribute2
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.attribute3
     *
     * @return the value of spu_complete.attribute3
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.attribute3
     *
     * @param attribute3 the value for spu_complete.attribute3
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.attribute4
     *
     * @return the value of spu_complete.attribute4
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.attribute4
     *
     * @param attribute4 the value for spu_complete.attribute4
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.description
     *
     * @return the value of spu_complete.description
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.description
     *
     * @param description the value for spu_complete.description
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.photolist
     *
     * @return the value of spu_complete.photolist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getPhotolist() {
        return photolist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.photolist
     *
     * @param photolist the value for spu_complete.photolist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setPhotolist(String photolist) {
        this.photolist = photolist == null ? null : photolist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.videolist
     *
     * @return the value of spu_complete.videolist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getVideolist() {
        return videolist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.videolist
     *
     * @param videolist the value for spu_complete.videolist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setVideolist(String videolist) {
        this.videolist = videolist == null ? null : videolist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.reservelist
     *
     * @return the value of spu_complete.reservelist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public String getReservelist() {
        return reservelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.reservelist
     *
     * @param reservelist the value for spu_complete.reservelist
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setReservelist(String reservelist) {
        this.reservelist = reservelist == null ? null : reservelist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.create_time
     *
     * @return the value of spu_complete.create_time
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.create_time
     *
     * @param createTime the value for spu_complete.create_time
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu_complete.update_time
     *
     * @return the value of spu_complete.update_time
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu_complete.update_time
     *
     * @param updateTime the value for spu_complete.update_time
     *
     * @mbg.generated Tue Dec 10 21:25:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}