package com.yueshimall.dataobject;

import java.util.Date;

public class STORE {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.userid
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storename
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private String storename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.logo
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.description
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.goodidlist
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private String goodidlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.createtime
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.userid
     *
     * @return the value of store.userid
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.userid
     *
     * @param userid the value for store.userid
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storename
     *
     * @return the value of store.storename
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storename
     *
     * @param storename the value for store.storename
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.logo
     *
     * @return the value of store.logo
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.logo
     *
     * @param logo the value for store.logo
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.description
     *
     * @return the value of store.description
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public String getDescribe() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.description
     *
     * @param description the value for store.description
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setDescribe(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.goodidlist
     *
     * @return the value of store.goodidlist
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public String getGoodidlist() {
        return goodidlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.goodidlist
     *
     * @param goodidlist the value for store.goodidlist
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setGoodidlist(String goodidlist) {
        this.goodidlist = goodidlist == null ? null : goodidlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.createtime
     *
     * @return the value of store.createtime
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.createtime
     *
     * @param createtime the value for store.createtime
     *
     * @mbg.generated Mon Feb 17 10:28:27 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}